# Generated by Django 3.2.4 on 2021-06-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
